# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  # - MediumFollowersCountPlugin:
      # username: zhgchgli
  # Automatically fetch Github repo star count
  # - GithubRepoStarsCountPlugin:
     # - ZhgChgLi/ZMarkupParser
     # - ZhgChgLi/ZReviewTender
     # - ZhgChgLi/ZMediumToMarkdown
     # - ZhgChgLi/linkyee

# Google Analytics tracking id
#google_analytics_id:

# HTML Title
title: "icosane's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "icosane"

# Tagline section text
tagline: >-
    Python developer with experience in PyQt and SQL. Skilled in working with scientific computing libraries like NumPy and SciPy. Likes to write GUI apps for Windows.
    I also sometimes dabble into manga scanlation, doing translation (en->ru), editing and typesetting all by myself. 

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-windows"
      text: "eustoma <span class='link-button-text'>(Speech-to-text app)</span>"
      url: "https://github.com/icosane/eustoma"
      alt: "Yet another speech-to-text app, powered by faster-whisper and QFluentWidgets"
      title: "Yet another speech-to-text app, powered by faster-whisper and QFluentWidgets."
      target: "_blank"
  - link:
      icon: "fa-brands fa-windows"
      text: "celosia <span class='link-button-text'>(PDF/EPUB offline translator)</span>"
      url: "https://github.com/icosane/celosia"
      alt: "Translate PDF and EPUB files locally"
      title: "Translate PDF and EPUB files locally"
      target: "_blank"
  - link:
      icon: "fa-brands fa-windows"
      text: "alstroemeria <span class='link-button-text'>(Subtitle creation, translation and voiceover)</span>"
      url: "https://github.com/icosane/alstroemeria"
      alt: "Create and translate subtitles for any video, complete with voiceover capabilities. "
      title: "Create and translate subtitles for any video, complete with voiceover capabilities. "
      target: "_blank"
  - link:
      icon: "fa-brands fa-windows"
      text: "vervain <span class='link-button-text'>(Win32 app simulating dynamic models)</span>"
      url: "https://github.com/icosane/vervain"
      alt: "Win32 app simulating dynamic models (Rössler, Lorenz, Chen). Utilizes TensorFlow-based image recognition to detect synchronization from phase portraits"
      title: "Win32 app simulating dynamic models (Rössler, Lorenz, Chen). Utilizes TensorFlow-based image recognition to detect synchronization from phase portraits"
      target: "_blank"
  - link:
      icon: "fa-brands fa-android"
      text: "aubretia <span class='link-button-text'>(An image search application)</span>"
      url: "https://github.com/icosane/aubretia"
      alt: "An image search application built with Flutter."
      title: "An image search application built with Flutter."
      target: "_blank"
  - link:
        icon: "fa-brands fa-python"
        text: "esoragoto <span class='link-button-text'>(Web-based Kuramoto modeler)</span>"
        url: "https://github.com/icosane/esoragoto"
        alt: "Web-based Kuramoto modeler"
        title: "Web-based Kuramoto modeler"
        target: "_blank"
  - link:
        icon: "fa-solid fa-globe"
        text: "translations"
        url: "https://icosane.github.io/translations/"
        alt: "my scanlations"
        title: "my scanlations"
        target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/icosane"
      title: "GitHub"
      alt: "GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-telegram"
      url: "https://icosane.t.me"
      title: "Telegram"
      alt: "Telegram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:yureruhimawari@outlook.com"
      title: "Email"
      alt: "yureruhimawari@outlook.com"
      target: "_blank"

# Footer text
footer: >
    yep. most of my repos are named after flowers. it's confusing, bad for indexing, but i think it's cute. 

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://github.com/icosane" target="_blank">icosane</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
